"""GPIO Pins"""
STATUS_PIN = 5
RED_PIN = 6
GREEN_PIN = 13
UP_PIN = 17
DOWN_PIN = 18
BACK_PIN = 27
SELECT_PIN = 22

"""Button States"""
NONE = 0
UP = 1
DOWN = 2
BACK = 3
SELECT = 4

"""OLED Size"""
WIDTH = 128
HEIGHT = 64

"""Terminal Spacings"""
TERMINAL_LINE_SPACING = 11
TERMINAL_X_INDENT = 2
TERMINAL_Y_INDENT = -2
TERMINAL_NUM_LINES = 6

"""Menu Spacings"""
MENU_LINE_SPACING = 12
MENU_X_INDENT = 2
MENU_Y_INDENT = -2
MENU_NUM_LINES = 6

"""Serial Comms"""
#PORT = '/dev/ttyUSB0'
PORT = '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A904TIS2-if00-port0'
BAUD_RATE = 115200
TIMEOUT = 1

MODE_C10 = 0
MODE_C16 = 1
MODE_TEXT = ['C10', 'C16']

TYPE_RX = 0
TYPE_TX = 1
TYPE_TEXT = ['RX', 'TX']


"""Serial Commands"""
PING = 'p'
SET_MODE_C10 = 'm'
SET_MODE_C16 = 'M'
TRANSMIT = 't'
RECIEVE = 'r'
RECEIVE_REPEAT = 'R'
STOP = 'x'
COMMS_TEST = 't'
GET_VERSION = 'i'
GET_VOLTAGE = 'v'
GET_CURRENT = 'a'
GET_BUTTON_PRESS = 'b'

"""Interface Delays"""
STARTUP_DELAY = 0.2
