"""GPIO Pins"""
STATUS_PIN = 5
RED_PIN = 6
GREEN_PIN = 13
UP_PIN = 17
DOWN_PIN = 18
BACK_PIN = 27
SELECT_PIN = 22

"""Button States"""
NONE = 0
UP = 1
DOWN = 2
BACK = 3
SELECT = 4

"""OLED Size"""
WIDTH = 128
HEIGHT = 64

"""Terminal Spacings"""
TERMINAL_LINE_SPACING = 11
TERMINAL_X_INDENT = 2
TERMINAL_Y_INDENT = -2
TERMINAL_NUM_LINES = 6

"""Menu Spacings"""
MENU_LINE_SPACING = 12
MENU_X_INDENT = 2
MENU_Y_INDENT = -2
MENU_NUM_LINES = 6